// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: fzrpc.proto
#ifndef GRPC_fzrpc_2eproto__INCLUDED
#define GRPC_fzrpc_2eproto__INCLUDED

#include "fzrpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class FzService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RemoteCall(::grpc::ClientContext* context, const ::FzRequest& request, ::FzResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FzResponse>> AsyncRemoteCall(::grpc::ClientContext* context, const ::FzRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FzResponse>>(AsyncRemoteCallRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FzResponse>* AsyncRemoteCallRaw(::grpc::ClientContext* context, const ::FzRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RemoteCall(::grpc::ClientContext* context, const ::FzRequest& request, ::FzResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FzResponse>> AsyncRemoteCall(::grpc::ClientContext* context, const ::FzRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FzResponse>>(AsyncRemoteCallRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::FzResponse>* AsyncRemoteCallRaw(::grpc::ClientContext* context, const ::FzRequest& request, ::grpc::CompletionQueue* cq) override;
    const grpc::internal::RpcMethod rpcmethod_RemoteCall_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RemoteCall(::grpc::ServerContext* context, const ::FzRequest* request, ::FzResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RemoteCall() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* context, const ::FzRequest* request, ::FzResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteCall(::grpc::ServerContext* context, ::FzRequest* request, ::grpc::ServerAsyncResponseWriter< ::FzResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RemoteCall<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RemoteCall() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* context, const ::FzRequest* request, ::FzResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RemoteCall() {
      ::grpc::Service::MarkMethodStreamed(0,
        new grpc::internal::StreamedUnaryHandler< ::FzRequest, ::FzResponse>(std::bind(&WithStreamedUnaryMethod_RemoteCall<BaseClass>::StreamedRemoteCall, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* context, const ::FzRequest* request, ::FzResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemoteCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FzRequest,::FzResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RemoteCall<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RemoteCall<Service > StreamedService;
};


#endif  // GRPC_fzrpc_2eproto__INCLUDED
